parameters:
    pool: ''
    machine: ''
    tclibc: ''
    build_branch: ''

jobs:
- job: ${{ parameters.machine }}_${{ parameters.tclibc }}
  pool: ${{ parameters.pool }}
  timeoutInMinutes: 0

  steps:
  - template: steps_setup.yml
    parameters:
      machine: ${{ parameters.machine }}
      build_branch: $(Build.SourceBranchName)
      tclibc: ${{ parameters.tclibc }}

  - template: steps_build.yml
