trigger: none

schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

variables:
  - template: templates/variables.yml

jobs:
  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'qemuarm'

  - template: templates/build.yml
    parameters:
      pool:
        vmImage: 'ubuntu-20.04'
      buildtype: 'poky'
      machine: 'qemuarm64'
