trigger: none


schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

stages:
- stage: baremetal
  displayName: Baremetal
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-20.04'
        machine: 'qemuarm'
    - template: templates/build.yml
      parameters:
        pool:
            vmImage: 'ubuntu-20.04'
        machine: 'qemuarm64'