trigger: none


schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

stages:
- stage: qemuarm
  displayName: ARM
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-20.04'
        machine: 'qemuarm'
- stage: qemuarm64
  displayName: ARM64
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
            vmImage: 'ubuntu-20.04'
        machine: 'qemuarm64'
- stage: riscv64
  displayName: RISCV-64
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
            vmImage: 'ubuntu-20.04'
        machine: 'qemuriscv64'