trigger: none


schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

stages:
- stage: qemuarm
  displayName: ARM
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-latest'
        machine: 'qemuarmv5'

- stage: qemuarm64
  displayName: ARM64
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-latest'
        machine: 'qemuarm64'
