trigger: none


schedules:
- cron: "0 0 * * *"
  displayName: Daily build
  branches:
    include:
    - master
    - dunfell
  always: true

stages:
- stage: tclibc_newlib
  displayName: tclibc_newlib
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-20.04'
        machine: 'qemuarmv5'
        tclibc: 'newlib'
    - template: templates/build.yml
      parameters:
        pool:
            vmImage: 'ubuntu-20.04'
        machine: 'qemuarm64'
        tclibc: 'newlib'

- stage: tclibc_baremetal
  displayName: tclibc_baremetal
  dependsOn: []
  jobs:
    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-20.04'
        machine: 'qemuarmv5'
        tclibc: 'baremetal'

    - template: templates/build.yml
      parameters:
        pool:
          vmImage: 'ubuntu-20.04'
        machine: 'qemuarm64'
        tclibc: 'baremetal'
